Calc tests lessons 1-3
kate-krasnoselska/web.test pull request #1
Opened 2021-03-01 14:53 UTC by kate-krasnoselska

Adde tests

2021-03-01 16:43 UTC, varajan requested changes
Good work, need some style changes, e.g.
- Remove empty lines at the end or beginning of the test;
- Add empty line before the test;
- Add empty lines inside test to create blocks of actions;
- Review test names.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            browser.FindElement(By.Id("login")).SendKeys("test");
I suggest adding an empty line here.

```suggestion
            browser.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            
            browser.FindElement(By.Id("login")).SendKeys("test");
```

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.AreEqual("10.00", actualInterest);
Separate actions from asserts. It will be easier to read the test:
```suggestion

            string actualIncome = browser.FindElement(By.Id("income")).GetAttribute("value");
            string actualInterest = browser.FindElement(By.Id("interest")).GetAttribute("value");

            Assert.AreEqual("110.00", actualIncome);
            Assert.AreEqual("10.00", actualInterest);
```

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            // NEED HELP couldn't manage this Test, unfortunately
Please remove unneeded comments.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        [Test]
Please add empty line before [Test]

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.IsFalse(d365 && d360);
You may add description to asserts to make failed tests easy to understand. These messages will be printed in test failed error.

```suggestion
            Assert.IsTrue(d365 || d360, "At least one option should be selected.");
            Assert.IsFalse(d365 && d360, "Only one option should be selected.");
```

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            // NEED HELP how to skip required field properly?
Empty line and unneeded comment.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
Please remove this empty line.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        [Test]
Please add empty line before [Test]

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            string actual = browser.FindElement(By.XPath("/html/body/div/div/table/tbody/tr[7]/th[1]")).GetAttribute("aalign");
The test should retrieve a valid attribute value.

```suggestion
            string actual = browser.FindElement(By.XPath("/html/body/div/div/table/tbody/tr[7]/th[1]")).GetAttribute("align");
```

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        } */
Please remove these commented code, if it is not needed.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        public void PositiveTestStartDateIsMandatoryField()
Please review test names.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +        [Obsolete]
Please remove 'obsolete' key.

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +            .Until(ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.Id("remindBtn")));
```suggestion
            new WebDriverWait(browser, TimeSpan.FromSeconds(10))
            .Until(SeleniumExtras.WaitHelpers.ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.Id("remindBtn")));
```

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +            string LoginName = browser.FindElement(By.ClassName("user")).GetAttribute ("innerText");
Please remove space after 'GetAttribute'

```suggestion
            string LoginName = browser.FindElement(By.ClassName("user")).GetAttribute("innerText");
```

2021-03-01 16:43 UTC, varajan commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +        [Test]
Please remove empty lines in the end of the test (before '}' ) and add ones before tests (before '[Test]')

2021-03-07 10:43 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +        [Test]
done

2021-03-07 10:52 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +            string LoginName = browser.FindElement(By.ClassName("user")).GetAttribute ("innerText");
done

2021-03-07 10:54 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +            .Until(ExpectedConditions.VisibilityOfAllElementsLocatedBy(By.Id("remindBtn")));
done

2021-03-07 10:54 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/LoginPageTests.cs
> +        [Obsolete]
done

2021-03-07 11:00 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        public void PositiveTestStartDateIsMandatoryField()
done

2021-03-07 11:02 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:03 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            browser.FindElement(By.Id("login")).SendKeys("test");
done

2021-03-07 11:04 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:04 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:07 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.AreEqual("10.00", actualInterest);
done

2021-03-07 11:07 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:07 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:07 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:07 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            // NEED HELP couldn't manage this Test, unfortunately
done

2021-03-07 11:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:11 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:11 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        [Test]
done

2021-03-07 11:12 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        } */
done

2021-03-07 11:13 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        [Test]
done

2021-03-07 11:13 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +
done

2021-03-07 11:13 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            // NEED HELP how to skip required field properly?
done

2021-03-07 11:18 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.IsFalse(d365 && d360);
I have added those messages as //comments temporarily. The app underlines it. NEED HELP how to insert them as messages correctly. 

            Assert.IsTrue(d365 || d360); //"At least one option should be selected."
            Assert.IsFalse(d365 && d360); //"Only one option should be selected."

2021-03-07 11:21 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            string actual = browser.FindElement(By.XPath("/html/body/div/div/table/tbody/tr[7]/th[1]")).GetAttribute("aalign");
done

2021-03-10 13:09 UTC, varajan approved these changes

2021-03-10 13:09 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        public void BeforeEachTest()
looks good

2021-03-10 13:09 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +        {
```suggestion
        public voID AfterEachTest()
        {
```

2021-03-10 13:11 UTC, merged