Settings page object
kate-krasnoselska/web.test pull request #45
Opened 2021-04-19 14:41 UTC by kate-krasnoselska

Hi! Please check my progress

2021-04-19 19:04 UTC, varajan requested changes
I am pretty happy to see that you've removed commented code.

2021-04-19 19:04 UTC, varajan commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
>              browser.SwitchTo().Alert().Accept();
It's better to make the 'LogoutBtn' private and add a method 'Logout':
```
public void Logout()
{
    // click logout button
    // accept alert
}
```

2021-04-19 19:04 UTC, varajan commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
>              browser.SwitchTo().Alert().Accept();
Same here: it's better to hide the 'SaveBtn' with 'private' attribute and add 'Save' method to SettingsPage.

2021-04-19 19:04 UTC, varajan commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
>              numberFormatSelect.SelectByText(format);
All, that you need or do on the 'Settings' page should be added to the 'SettingsPage', e.g. web controls or actions. E.g.

public IWebElement LogoutBtn
public Select Currency
public void SelectDateFormat(string format)

2021-04-21 06:21 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
>              browser.SwitchTo().Alert().Accept();
done

2021-04-21 06:21 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
>              browser.SwitchTo().Alert().Accept();
done

2021-04-21 09:31 UTC, varajan commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
> +            new SettingsPage(browser).Logout();
```
            SettingsPage settingsPage = new SettingsPage(browser);
            settingsPage.Logout();
```
or
```
            new SettingsPage(browser).Logout();
```

2021-04-21 11:41 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
> +            new SettingsPage(browser).Logout();
done! thanks

2021-04-27 06:09 UTC, varajan requested changes
Good work, I see only one improvement.

2021-04-27 06:09 UTC, varajan commented on Calculator.Tests/Calculator.Tests/SettingsPageTests.cs
> +
Extra lines. Please remove.

2021-04-27 06:09 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Thread.Sleep(1000);
Try to replace this 'sleep' with Explicit Wait:

```
new WebDriverWait(<webdriver>, <timeout>).Until(<button is enabled>)
```
Why the Explicit Wait is better than Sleep()?
The condition is usually met earlier and the test doesn't wait full <timeout>, e.g. just 500 ms instead of 1000 ms. Yep, it's not a big difference, but if you have 100 tests or more and each have few unneeded delays the full regression became longer and longer. In some cases the website works a little slower forcing you to increase the 'timeout' from 1000 to 2000, or more. And after some time it works again fast (500 ms), but you already have Sleep(2000). So the test do nothing for 1.5 seconds each time.

2021-04-28 11:32 UTC, merged