Calculator page object
kate-krasnoselska/web.test pull request #48
Opened 2021-05-19 09:45 UTC by kate-krasnoselska

Hi! Please check my work. I rewrote Calculator Page tests to use Page Object

2021-05-19 11:06 UTC, varajan requested changes
Nice work, will help you to resolve the issues.

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
If you use the same page few times, create a variable for this page and use it.

```suggestion
            CalculatorPage calculatorPage = new CalculatorPage(browser)
            calculatorPage
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Thread.Sleep(1000);
You should move this 'pause' to the 'Calculate' method.

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/Pages/CalculatorPage.cs
> +        public IWebElement ActualIncome => driver.FindElement(By.XPath("//input [@id = 'income']"));
It's better to change this property type to 'string' and return the text value. This works if you don't need the control itself, only its text.
```suggestion
        public string ActualIncome => driver.FindElement(By.XPath("//input [@id = 'income']")).GetAttribute("value");
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
Too many 'new CalculatorPage' calls in this test. Please create a variable 'calculatorPage' and use it.

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
```suggestion
            calculatorPage
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
```suggestion
            calculatorPage
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.AreEqual(false, calculatorPage.CalculateBtn.Enabled);
For boolean checks you should use 'IsTrue' or 'IsFalse'

```suggestion
            Assert.IsFalse(calculatorPage.CalculateBtn.Enabled);
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
```suggestion
            calculatorPage
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.AreEqual(false, calculatorPage.CalculateBtn.Enabled);
```suggestion
            Assert.IsFalse(calculatorPage.CalculateBtn.Enabled);
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
>              SelectElement daySelect = new SelectElement(element: browser.FindElement(By.XPath("//select [@id = 'day']")));
Note: no 'browser.FindElement' are allowed in tests. Please move this to appropriate page as control or method. Also, we can do it on the next call.

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/Pages/CalculatorPage.cs
> +        public IWebElement DepositAmountFld => driver.FindElement(By.XPath("//td[2]//input[@id = 'amount']"));
```suggestion
        public IWebElement DepositAmountFld => driver.FindElement(By.XPath("//input[@id = 'amount']"));
```

2021-05-19 11:06 UTC, varajan commented on Calculator.Tests/Calculator.Tests/Pages/CalculatorPage.cs
> +            FinancialYearRadio365.Click();
```suggestion
        public void EnterCalculatorData(string deposit, string rate, string term, bool year365)
        {
            DepositAmountFld.SendKeys(deposit);
            RateOfInterestFld.SendKeys(rate);
            InvestmentTermFld.SendKeys(term);
            if (year365)
            {
                FinancialYearRadio365.Click();
            }
            else
            {
                FinancialYearRadio360.Click();
            }
```

2021-05-23 02:52 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/Pages/CalculatorPage.cs
> +        public IWebElement ActualIncome => driver.FindElement(By.XPath("//input [@id = 'income']"));
done, thanks

2021-05-23 02:54 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Thread.Sleep(1000);
it is already done, idk why you see it
 ` public void Calculate()
        {
            CalculateBtn.Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
            .Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(CalculateBtnLocator));
            Thread.Sleep(1000);
        }`

2021-05-23 02:55 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
sorry, could not understand this, let's discuss

2021-05-23 03:07 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.AreEqual(false, calculatorPage.CalculateBtn.Enabled);
done, thanks

2021-05-23 03:15 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/Pages/CalculatorPage.cs
> +            FinancialYearRadio365.Click();
wow! cool! thank you, done

2021-05-23 03:19 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/Pages/CalculatorPage.cs
> +        public IWebElement DepositAmountFld => driver.FindElement(By.XPath("//td[2]//input[@id = 'amount']"));
done, thanks!

2021-05-23 03:45 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
>              SelectElement daySelect = new SelectElement(element: browser.FindElement(By.XPath("//select [@id = 'day']")));
ok, let's do it together

2021-05-23 03:50 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            Assert.AreEqual(false, calculatorPage.CalculateBtn.Enabled);
done, thanks

2021-05-23 04:05 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
i did it as well as I could understand you, let's discuss on call
```CalculatorPage calculatorPage = new CalculatorPage(browser);
            calculatorPage
                .EnterCalculatorData("100", "10", "365", true);

            calculatorPage
                .Calculate();
```

2021-05-23 04:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
did it, let's discuss

2021-05-23 04:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
did

2021-05-23 04:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
did

2021-05-23 04:10 UTC, kate-krasnoselska commented on Calculator.Tests/Calculator.Tests/CalculatorTests.cs
> +            new CalculatorPage(browser)
did

2021-05-30 11:27 UTC, merged